### ISSUE TITLE
building new dictionary

### ISSUE THREAD

**Issue by etheleon** [xiechaos/ribotagger#3]
hi XC, 

Trying to create new dictionary. I'm using 119 to test the process. 
Downloaded the file [SILVA_119_SSURef_tax_silva.fasta.gz](https://www.arb-silva.de/fileadmin/silva_databases/release_119/Exports/SILVA_119_SSURef_tax_silva.fasta.gz) and tried running the `misc/dict.builder/silva.dict.sh` script. 

``` bash
SILVA='data/SILVA_119_SSURef_tax_silva.fasta'
./script/ribo.pl --print-tag --print-long --print-head --se 0 -i $SILVA -o temp -r v4 > dict/raw/silva.v4
```

however the output file `dict/raw/silva.v4` is empty 0Bytes wad is the problem?

below is the directory structure of the dict.builder folder insider misc

```
.
├── data
│   ├── SILVA_119_SSURef_tax_silva.fasta
│   ├── SILVA_119_SSURef_tax_silva_trunc.fasta
│   ├── SSURef_115_tax_silva.fasta
│   └── nohup.out
├── dict
│   ├── raw
│   │   ├── silva.v4
│   │   ├── silva.v5
│   │   ├── silva.v6
│   │   └── silva.v7
│   ├── silva.long.v4
│   ├── silva.long.v5
│   ├── silva.long.v6
│   ├── silva.long.v7
│   ├── silva.tag.v4
│   ├── silva.tag.v5
│   ├── silva.tag.v6
│   └── silva.tag.v7
├── greengenes.dict.sh
├── greengenes.pl
├── nohup.out
├── script
│   ├── dict
│   │   ├── silva.long.v4
│   │   ├── silva.long.v5
│   │   ├── silva.long.v6
│   │   ├── silva.long.v7
│   │   ├── silva.tag.v4
│   │   ├── silva.tag.v5
│   │   ├── silva.tag.v6
│   │   └── silva.tag.v7
│   ├── dict.builder
│   │   ├── lite.pl
│   │   └── silva.pl
│   └── ribo.pl
├── silva.dict.sh
├── silva.rank.fix.pl
└── temp
```

PS.
ribo.pl was copied from `ribotagger/ribotagger.pl`

**Comment by etheleon** [comment]
wrote a short converter, seems like ribotagger requires DNA input instead of RNA.

``` perl
#!/usr/bin/env perl

use Modern::Perl '2015';
use Bio::SeqIO;

my $in = Bio::SeqIO->new(-file => $ARGV[0], -format => 'fasta');
my $out = Bio::SeqIO->new(-file => '>output.fna', -format => 'fasta');

while(my $seq = $in->next_seq){
    my $theSeq = $seq->seq();
    $theSeq =~ tr/AUCGaucg/ATCGatcg/;
    $seq->seq($theSeq);
    $out->write_seq($seq);
}
```

**Comment by etheleon** [comment]
the output tag file look like this `dict/silva.tag.v4`

version which comes with ribotagger

```
TCTATAATGTCTGAGGTATAAGTGCAGTGCTCA       k__Bacteria++1--1       p__Tenericutes++1--1    c__Mollicutes++1--1  o__Acholeplasmatales++1--1      f__Acholeplasmataceae++1--1     g__Acholeplasma++1--1
```

my version 

```
Bacteria;Actinobacteria;Actinobacteria;Micrococcales;Rarobacteraceae;   663     family          119     1       1       1       phylum  1       Actinobacteria  Bacteria;Actinobacteria;        157
```

**Comment by etheleon** [comment]
k, it was my fault, ignore the above

**Comment by hites77** [comment]
Hi etheleon,  how did you correct the output format ?
I am getting like this
TTTTTTAAGTCTGATGTGAAAGCCCACGGCTCA       97879   97879   97879   domain  1       Bacteria        Bacteria;       1826266
TTTTTTAAGTCTGATGTGAAAGCCCACGGCTCA       97879   97879   97878   phylum  1       Firmicutes      Bacteria;Firmicutes;    570113
TTTTTTAAGTCTGATGTGAAAGCCCACGGCTCA       97879   97879   97877   class   1       Bacilli Bacteria;Firmicutes;Bacilli;    361494
